import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { Check, ChevronRight, CircleAlert, FlaskConical, KeyRound, LockKeyhole, Radio, RefreshCw, ShieldCheck, Sparkles, Wallet } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getHealth, getMetrics, getProofPlan, saveReceipt } from './lib/api'
import { loadWitness, rotateWitness, saveWitness, createWitness, type LocalWitness } from './lib/private-state'
import type { Connection, Network, ProofPlan, ProofStage, PublicMetrics, ServiceHealth } from './lib/types'
import { callEligibilityCircuit, connectWallet, discoverWallets } from './lib/wallet'

const policy = 'Currently enrolled students aged 18 or over may access the campus night lab.'
const stations = ['Requirement', 'Local record', 'Privacy boundary', 'Connect 1AM', 'Generate proof', 'Receipt']

function Tag({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'safe' | 'public' | 'pending' }) { return <span className={`tag ${tone}`}>{children}</span> }

export function App() {
  const reduceMotion = useReducedMotion()
  const [network, setNetwork] = useState<Network>('preview')
  const [witness, setWitness] = useState<LocalWitness | null>(null)
  const [connection, setConnection] = useState<Connection | null>(null)
  const [stage, setStage] = useState<ProofStage>('idle')
  const [plan, setPlan] = useState<ProofPlan | null>(null)
  const [message, setMessage] = useState('No transaction has been submitted.')
  const [receipt, setReceipt] = useState<string | null>(null)
  const [metrics, setMetrics] = useState<PublicMetrics>({ verified_proofs: 0, successful_proofs: 0, private_records_stored: 0 })
  const [serviceHealth, setServiceHealth] = useState<ServiceHealth | null>(null)

  useEffect(() => { const stored = loadWitness(); const next = stored ?? createWitness(); if (!stored) saveWitness(next); setWitness(next) }, [])
  useEffect(() => { let active = true; const refreshPublicState = async () => { try { const [nextMetrics, nextHealth] = await Promise.all([getMetrics(), getHealth()]); if (active) { setMetrics(nextMetrics); setServiceHealth(nextHealth) } } catch { if (active) setServiceHealth({ service: 'vera-api', status: 'degraded', database: 'unreachable' }) } }; void refreshPublicState(); const interval = window.setInterval(() => { void refreshPublicState() }, 30_000); return () => { active = false; window.clearInterval(interval) } }, [])
  const loadPlan = async () => { setStage('review'); try { setPlan(await getProofPlan(policy)); setMessage('Proof plan calibrated. Your local record was not sent.') } catch (error) { setStage('error'); setMessage(error instanceof Error ? error.message : 'Unable to calibrate plan.') } }
  const connect = async () => { setStage('connecting'); try { setConnection(await connectWallet(network)); setStage('review'); setMessage('1AM wallet connected for this session only.') } catch (error) { setStage('error'); setMessage(error instanceof Error ? error.message : 'Wallet connection failed.') } }
  const prove = async () => { if (!connection || !witness) return; setStage('proving'); setMessage('Generating a zero-knowledge proof in your wallet…'); try { const result = await callEligibilityCircuit(connection, witness, 'campus-night-lab'); setStage('finalizing'); setMessage('Submitted. Waiting for finalized confirmation…'); setReceipt(result.transactionId); try { await saveReceipt(result.transactionId, 'campus-night-lab', policy); setMessage('Finalized public receipt available. The public aggregate has been updated.') } catch { setMessage('Transaction finalized. Public receipt publishing will retry when the service is available.') } setStage('success'); try { setMetrics(await getMetrics()) } catch { /* The finalized chain receipt remains valid without API metrics. */ } } catch (error) { setStage('error'); setMessage(error instanceof Error ? error.message : 'Proof failed.') } }
  const switchNetwork = (value: Network) => { setNetwork(value); setConnection(null); setReceipt(null); setStage('idle'); setMessage('Network changed. Wallet session reset for your privacy.') }
  const rotate = () => { setWitness(rotateWitness()); setReceipt(null); setMessage('Local proof material replaced on this device.') }

  return <main className="shell">
    <aside className="rail"><div className="brand"><FlaskConical size={23}/><span>VERA</span></div><p className="rail-label">STUDENT PROOF STATION</p><nav>{stations.map((item, index) => <a href={`#${item.toLowerCase().replace(' ', '-')}`} key={item} className={index === 0 ? 'active' : ''}><b>{String(index + 1).padStart(2, '0')}</b>{item}<ChevronRight size={15}/></a>)}</nav><div className="rail-foot"><Tag tone="safe">LOCAL-FIRST</Tag><p>v0.1 / preview-ready</p></div></aside>
    <section className="workspace">
      <header className="topbar"><div><p className="eyebrow">CALIBRATED ACCESS INSTRUMENT</p><h1>Prove the rule.<br/>Keep your record.</h1></div><div className="network-control"><nav className="section-nav" aria-label="Page sections"><a href="#student-guide">Student guide</a><a href="#verifier-console">For verifiers</a><a href="#learn">Learn</a></nav><label>NETWORK</label><select value={network} onChange={(event) => switchNetwork(event.target.value as Network)} aria-label="Select network"><option value="preview">Preview</option><option value="preprod">Preprod</option></select><span className={connection ? 'status online' : 'status'}>{connection ? connection.provider.name : `${discoverWallets().length} wallets found`}</span><span className={serviceHealth?.status === 'ok' ? 'service-status online' : 'service-status'}>{serviceHealth?.status === 'ok' ? 'PUBLIC SERVICE READY' : 'PUBLIC SERVICE CHECKING'}</span></div></header>
      <section className="calibration panel" id="requirement"><div className="number">01 / PUBLIC REQUIREMENT</div><div><h2>Campus Night Lab</h2><p>{policy}</p></div><Tag tone="public">VERIFIER CAN READ</Tag></section>
      <section className="proof-grid">
        <motion.article className="panel privacy" id="privacy-boundary" initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} animate={{ opacity: 1, y: 0 }}><div className="number">02 / PRIVACY BOUNDARY</div><div className="boundary"><div className="private-zone"><LockKeyhole/><h3>Local only</h3><ul><li>Date of birth</li><li>Student identifier</li><li>Credential commitment</li><li>Secret proof nonce</li></ul><Tag tone="safe">STAYS ON THIS DEVICE</Tag></div><div className="seal"><span>SEALED</span><i></i><ShieldCheck/></div><div className="public-zone"><Radio/><h3>Public receipt</h3><ul><li>Eligible: yes / no</li><li>Scope-bound anti-replay marker</li><li>Finalized transaction ID</li></ul><Tag tone="public">VERIFIER CAN LEARN</Tag></div></div><p className="fineprint">The verifier checks the rule. They do not receive your student record.</p></motion.article>
        <article className="panel steps" id="local-record"><div className="number">03 / PROOF SEQUENCE</div><ol><li className={witness ? 'done' : ''}><b><Check size={15}/></b><span><strong>Local record prepared</strong><small>{witness ? `Rotated ${new Date(witness.createdAt).toLocaleDateString()}` : 'Preparing…'}</small></span><button onClick={rotate} className="icon-button" aria-label="Replace local material"><RefreshCw size={16}/></button></li><li className={plan ? 'done' : ''}><b>{plan ? <Check size={15}/> : '2'}</b><span><strong>Review the proof plan</strong><small>Only the public policy goes to Gemini.</small></span><button className="small-button" onClick={loadPlan}>Review</button></li><li className={connection ? 'done' : ''}><b>{connection ? <Check size={15}/> : '3'}</b><span><strong>Connect your 1AM wallet</strong><small>{connection ? `${connection.provider.name} / ${connection.network}` : 'Session-only connection.'}</small></span><button className="small-button" onClick={connect}>{connection ? 'Connected' : 'Connect'}</button></li><li className={receipt ? 'done' : ''}><b>{receipt ? <Check size={15}/> : '4'}</b><span><strong>Generate proof and finalize</strong><small>Nothing is submitted until your wallet confirms.</small></span><button className="small-button primary" disabled={!connection || stage === 'proving'} onClick={prove}>Generate</button></li></ol><AnimatePresence>{stage === 'proving' && <motion.div className="trace" initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} exit={{ opacity: 0 }} transition={{ duration: reduceMotion ? 0 : 1.2 }}/>}</AnimatePresence><p className={stage === 'error' ? 'diagnostic error' : 'diagnostic'}>{stage === 'error' ? <CircleAlert size={16}/> : <Sparkles size={16}/>} {message}</p></article>
      </section>
      <section className="lower-grid"><article className="panel assistant"><div className="number">04 / PUBLIC-POLICY ASSISTANT</div><h3><Sparkles size={18}/> Gemini boundary</h3>{plan ? <><p>{plan.summary}</p><div className="columns"><div><b>Disclosed</b>{plan.disclosed.map(x => <span key={x}>{x}</span>)}</div><div><b>Private</b>{plan.private.map(x => <span key={x}>{x}</span>)}</div></div><p className="fineprint">{plan.caution}</p></> : <p>Ask the assistant to translate the published policy into a plain-language proof plan. It cannot inspect your credential.</p>}</article><article className="panel wallet" id="connect-1am"><div className="number">05 / WALLET INSTRUMENT</div><Wallet size={22}/><h3>{connection ? connection.provider.name : '1AM not connected'}</h3><p>{connection ? `Network ${connection.network}; session stays in this browser tab.` : 'Connect only when you are ready to make a real circuit call.'}</p>{connection && <button className="text-button" onClick={() => { setConnection(null); setReceipt(null); setMessage('Wallet session disconnected.') }}>Disconnect session</button>}</article><article className="panel receipt" id="receipt"><div className="number">06 / PUBLIC RECEIPT</div><KeyRound size={22}/><h3>{receipt ? 'Finalized transaction' : 'No receipt yet'}</h3><p>{receipt ? receipt : 'A receipt appears only after Midnight finalizes a real submitted transaction.'}</p><Tag tone={receipt ? 'safe' : 'neutral'}>{receipt ? 'FINALIZED' : 'NOT SUBMITTED'}</Tag></article></section>
      <section className="metrics" aria-label="Public metrics"><div><b>{metrics.private_records_stored}</b><span>private records stored</span></div><div><b>{metrics.verified_proofs}</b><span>verified proofs</span></div><div><b>{metrics.successful_proofs}</b><span>successful proofs</span></div><div><b>0</b><span>replayed proofs accepted</span></div></section>
      <section className="story-section" id="student-guide"><div className="story-intro"><p className="number">07 / STUDENT FIELD GUIDE</p><h2>Your record never leaves the instrument.</h2><p>VERA turns an intimidating proof into a short, transparent sequence. Every station explains what happens before your wallet is asked to do anything.</p></div><div className="guide-grid"><article><b>01</b><h3>Read the rule</h3><p>Start with the verifier’s public requirement. If it asks for more than an outcome, stop and ask why.</p></article><article><b>02</b><h3>Inspect the boundary</h3><p>Green is local. Blue is public. The seal is the point where a proof replaces the original record.</p></article><article><b>03</b><h3>Approve deliberately</h3><p>1AM is connected only for this session. A receipt appears only after a real network finalization.</p></article></div></section>
      <section className="story-section verifier-section" id="verifier-console"><div className="story-intro"><p className="number">08 / VERIFIER CONSOLE</p><h2>Publish a fair rule, not a data request.</h2><p>Design access around the smallest answer you need. VERA makes the disclosure scope visible to students before any proof begins.</p><button className="small-button" onClick={loadPlan}>Inspect this proof plan</button></div><article className="policy-sheet"><div className="sheet-rule"><span>POLICY INPUT</span><b>ENROLLED + AGE 18+</b></div><div className="sheet-rule"><span>PROOF OUTPUT</span><b>ELIGIBLE: YES / NO</b></div><div className="sheet-rule"><span>PUBLIC LOG</span><b>SCOPED NULLIFIER + RECEIPT</b></div><p>Do not request student numbers, documents, wallets, or source attributes when a decision is sufficient.</p></article></section>
      <section className="story-section learn-section" id="learn"><div className="story-intro"><p className="number">09 / HOW THE INSTRUMENT WORKS</p><h2>Zero knowledge, in student language.</h2></div><div className="learn-rows"><article><span>01</span><div><h3>Your credential stays local</h3><p>It is used as a private input. VERA does not upload it to the API, Gemini, verifier, or public chain.</p></div></article><article><span>02</span><div><h3>The proof answers only the rule</h3><p>Midnight checks the conditions and reveals an outcome, without making the ingredients visible.</p></div></article><article><span>03</span><div><h3>A scoped marker prevents reuse</h3><p>A nullifier lets the same verifier reject a replay without becoming a cross-site tracking identifier.</p></div></article></div></section>
      <footer><div className="brand"><FlaskConical size={19}/><span>VERA</span></div><p>Student Proof Station / Built for Midnight Preview &amp; Preprod</p><a href="#requirement">Return to instrument ↑</a></footer>
    </section>
  </main>
}
